"""Initial migration with all models

Revision ID: 25932f1d6593
Revises: 
Create Date: 2025-05-29 03:48:26.341622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25932f1d6593'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('linkedin_url', sa.String(length=255), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_linkedin_url'), ['linkedin_url'], unique=True)

    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_education_profile_id'), ['profile_id'], unique=False)

    op.create_table('job_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_url', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('role_type', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_history_profile_id'), ['profile_id'], unique=False)

    op.create_table('profile_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'tag_name', name='uix_profile_tag')
    )
    with op.batch_alter_table('profile_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_tags_profile_id'), ['profile_id'], unique=False)

    op.create_table('profile_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('data_snapshot', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'version_number', name='uix_profile_version')
    )
    with op.batch_alter_table('profile_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_versions_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_versions_profile_id'))

    op.drop_table('profile_versions')
    with op.batch_alter_table('profile_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_tags_profile_id'))

    op.drop_table('profile_tags')
    with op.batch_alter_table('job_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_history_profile_id'))

    op.drop_table('job_history')
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_education_profile_id'))

    op.drop_table('education')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_linkedin_url'))

    op.drop_table('profiles')
    # ### end Alembic commands ###
